services:
  - type: web
    name: keramika-yunony-bot
    runtime: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        value: 8259914390:AAFLigXIVu0Eq4yb6Ndqm-g1oBxwQQHF9D4
      - key: ADMIN_USERNAME
        value: @sergeynnn03
      - key: ADMIN_ID
        value: 810412477
      - key: PYTHON_VERSION
        value: 3.11.8  # Явно указываем стабильную версию